---
title: "HW2 - MA232"
author: "Jerry Cheng"
date: "2/23/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\centerline{I pledge my honor that I have abided by the Stevens Honor System.} 
**Problem 1**  

\[
\ A = 
  \left[
    \begin {array}{ccc}
            2 & 1 & 0  \\
            -2 & 0 & 1   \\
            8 & 5 & 3  \\
    \end{array}
  \right]
\
\ I =
  \left[
    \begin {array}{ccc}
            1 & 0 & 0  \\
            0 & 1 & 0   \\
            0 & 0 & 1  \\
    \end{array}
  \right]
\]

$R_2 = R_2 + R_1$

\[
\ A_{21} = 
  \left[
    \begin {array}{ccc}
            2 & 1 & 0  \\
            0 & 1 & 1   \\
            8 & 5 & 3  \\
    \end{array}
  \right]
\
\ E_{21} =
  \left[
    \begin {array}{ccc}
            1 & 0 & 0  \\
            1 & 1 & 0   \\
            0 & 0 & 1  \\
    \end{array}
  \right]
\]

$R_3 = R_3 + 4R_1$

\[
\ A_{31} = 
  \left[
    \begin {array}{ccc}
            2 & 1 & 0  \\
            0 & 1 & 1   \\
            0 & 1 & 3  \\
    \end{array}
  \right]
\
\ E_{31} =
  \left[
    \begin {array}{ccc}
            1 & 0 & 0  \\
            0 & 1 & 0   \\
            -4 & 0 & 1  \\
    \end{array}
  \right]
\]

$E = E_{21} \cdot E_{31} =$

\[
  E = 
  \left[
    \begin {array}{ccc}
            1 & 0 & 0  \\
            1 & 1 & 0   \\
            -4 & 0 & 1  \\
    \end{array}
  \right]
\
\]

$E * A =$

\[
  \left[
    \begin {array}{ccc}
            1 & 0 & 0  \\
            1 & 1 & 0   \\
            -4 & 0 & 1  \\
    \end{array}
  \right]
\
  \left[
    \begin {array}{ccc}
            2 & 1 & 0  \\
            -2 & 0 & 1   \\
            8 & 5 & 3  \\
    \end{array}
  \right]
\]

\[
  = 
  \left[
    \begin {array}{ccc}
            2 & 1 & 0  \\
            0 & 1 & 1   \\
            0 & 1 & 3  \\
    \end{array}
  \right]
\
\]

\newpage
**Problem 2**
\[ A =
\left[
\begin{array}{cccc|cccc}
0 & 0 & 0  & 2 & 1 & 0 & 0 & 0 \\
0 & 0 & 3  & 0 & 0 & 1 & 0 & 0\\
0 & 4 & 0 & 0 & 0 & 0 & 1 & 0\\
5 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
\end{array}
\right]
\]

$R_1 = R_1 + \frac{1}{5}R_4$  
$R_2 = R_2 + \frac{1}{4}R_3$  
$R_3 = R_3 + \frac{1}{3}R_2$  
$R_4 = R_4 + \frac{1}{2}R_1$  

\[ 
\left[
\begin{array}{cccc|cccc}
1 & 0 & 0  & 2 & 1 & 0 & 0 & \frac{1}{5} \\
0 & 1 & 3  & 0 & 0 & 1 & \frac{1}{4} & 0\\
0 & 4 & 1 & 0 & 0 & \frac{1}{3} & 1 & 0\\
5 & 0 & 0 & 1 & \frac{1}{2} & 0 & 0 & 1\\
\end{array}
\right]
\]

$R_4 = R_4 - 5R_1$  
$R_3 = R3 - 4R_2$  
$R_2 = R_2 - 3R_3$  
$R_1 = R_1 - 2R_5$  

\[ 
\left[
\begin{array}{cccc|cccc}
1 & 0 & 0  & 0 & 0 & 0 & 0 & \frac{1}{5} \\
0 & 1 & 0  & 0 & 0 & 0 & \frac{1}{4} & 0\\
0 & 0 & 1 & 0 & 0 & \frac{1}{3} & 0 & 0\\
0 & 0 & 0 & 1 & \frac{1}{2} & 0 & 0 & 0\\
\end{array}
\right]
\]

$A^{-1} =$

\[ 
\left[
\begin{array}{cccc}
0 & 0 & 0 & \frac{1}{5} \\
0 & 0 & \frac{1}{4} & 0\\
0 & \frac{1}{3} & 0 & 0\\
\frac{1}{2} & 0 & 0 & 0\\
\end{array}
\right]
\]

\newpage

\[ B =
\left[
\begin{array}{cccc|cccc}
3 & 2 & 0  & 0 & 1 & 0 & 0 & 0 \\
4 & 3 & 0  & 0 & 0 & 1 & 0 & 0\\
0 & 0 & 6 & 5 & 0 & 0 & 1 & 0\\
0 & 0 & 7 & 6 & 0 & 0 & 0 & 1\\
\end{array}
\right]
\]

$R_4=R_4-R_3$

\[
\left[
\begin{array}{cccc|cccc}
3 & 2 & 0  & 0 & 1 & 0 & 0 & 0 \\
4 & 3 & 0  & 0 & 0 & 1 & 0 & 0\\
0 & 0 & 6 & 5 & 0 & 0 & 1 & 0\\
0 & 0 & 1 & 1 & 0 & 0 & -1 & 1\\
\end{array}
\right]
\]

$R_3=R_3-5R_4$

\[
\left[
\begin{array}{cccc|cccc}
3 & 2 & 0  & 0 & 1 & 0 & 0 & 0 \\
4 & 3 & 0  & 0 & 0 & 1 & 0 & 0\\
0 & 0 & 1 & 0  & 0 & 0 & 6 & -5\\
0 & 0 & 1 & 1  & 0 & 0 & -1 & 1\\
\end{array}
\right]
\]

$R_4=R_4-R_3$  
$R_2=R_2-R_1$

\[
\left[
\begin{array}{cccc|cccc}
3 & 2 & 0  & 0 & 1 & 0 & 0 & 0 \\
1 & 1 & 0  & 0 & -1 & 1 & 0 & 0\\
0 & 0 & 1 & 0  & 0 & 0 & 6 & -5\\
0 & 0 & 0 & 1  & 0 & 0 & -7 & 6\\
\end{array}
\right]
\]

$R_1=R_1-2R_2$  
$R_2=R_2-R_1$

\[
\left[
\begin{array}{cccc|cccc}
1 & 0 & 0  & 0 & 3 & -2 & 0 & 0 \\
0 & 1 & 0  & 0 & -4 & 3 & 0 & 0\\
0 & 0 & 1 & 0  & 0 & 0 & 6 & -5\\
0 & 0 & 0 & 1  & 0 & 0 & -7 & 6\\
\end{array}
\right]
\]

$B^{-1}=$

\[ 
\left[
\begin{array}{cccc}
3 & -2 & 0 & 0 \\
-4 & 3 & 0 & 0\\
0 & 0 & 6 & -5\\
0 & 0 & -7 & 6\\
\end{array}
\right]
\]

\newpage
**Problem 3**
